# https://goframe.org/docs/web/server-config-file-template
server:
  address: ":8000"
  openapiPath: "/api.json"
  swaggerPath: "/swagger"

# https://goframe.org/docs/core/glog-config
logger:
  level: "all"
  stdout: true

# https://goframe.org/docs/core/gdb-config-file
database:
  default:
    link: "mysql:root:root@tcp(127.0.0.1:3306)/capys?charset=utf8mb4&parseTime=true&loc=Local"
    debug: true

redis:
  default:
    address: 127.0.0.1:6379
    db: 0
