// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"capys/internal/dao/internal"
)

// userProblemDao is the data access object for the table user_problem.
// You can define custom methods on it to extend its functionality as needed.
type userProblemDao struct {
	*internal.UserProblemDao
}

var (
	// UserProblem is a globally accessible object for table user_problem operations.
	UserProblem = userProblemDao{internal.NewUserProblemDao()}
)

// Add your custom methods and functionality below.
