// =================================================================================
// This file is auto-generated by the GoFrame CLI tool. You may modify it as needed.
// =================================================================================

package dao

import (
	"capys/internal/dao/internal"
)

// userProblemRecordDao is the data access object for the table user_problem_record.
// You can define custom methods on it to extend its functionality as needed.
type userProblemRecordDao struct {
	*internal.UserProblemRecordDao
}

var (
	// UserProblemRecord is a globally accessible object for table user_problem_record operations.
	UserProblemRecord = userProblemRecordDao{internal.NewUserProblemRecordDao()}
)

// Add your custom methods and functionality below.
